### ISSUE TITLE
Allow `gswin64c` in restricted mode

### ISSUE THREAD

**Issue by bersbersbers** [ho-tex/pdfcrop#14]
`gswin64c` fails in restricted mode:

https://github.com/ho-tex/pdfcrop/blob/2ad5497487c78802f3dea0e86ff287deba414a22/pdfcrop.pl#L635-L639

**Comment by davidcarlisle** [comment]
@bersbersbers  agreed there seems no reason to allow gs and gswin32c but not gswin64c, I'll update

**Comment by kberry** [comment]
With the advent of 64-bit Windows in TL23 ... please apply/release this. Not that I care personally :).

**Comment by davidcarlisle** [comment]
@kberry  added in v1.41  although (r)pdfcrop isn't by default in shell_escape_commands

**Comment by kberry** [comment]
@kberry added in v1.41 although (r)pdfcrop isn't by default in
    shell_escape_commands

From my comment in texmf.cnf (from years ago, when we first added
repstopdf and the whole automatic eps->pdf conversion):

% rpdfcrop - maybe ok, but let's get experience with repstopdf first.

it seems it's never been there, and no one has asked for it.

So I'm not inclined to add it, although I don't see any obvious problem
with it.  Unlike epstopdf, it looks like arbitrary gs options aren't
allowed to be specified, so that eliminates one big pain that epstopdf
has to deal with.

At any rate, thanks for the new release. --thanks, karl.
