### ISSUE TITLE
Feature request: --quiet

### ISSUE THREAD

**Issue by ras52** [ho-tex/pdfcrop#7]
If you're invoking `pdfcrop` repeated in a script or a Makefile or similar, the repeated copyright message and pages written count can mask genuine errors.  Can we have a `--quiet` option to suppress them, please?

**Comment by kberry** [comment]
Here is a patch for this. (also updated the administrivia, in hopes.)

I also threw in an unrelated change (sorry, but it's trivial), to make pdfcrop --foo just say "try --help" instead of (annoyingly IMHO) printing the whole verbose help msg just because I made a mistake typing an option name. If you don't like that, feel free to leave that out.

[quietdiff.txt](https://github.com/ho-tex/pdfcrop/files/11224898/quietdiff.txt)

**Comment by davidcarlisle** [comment]
added in v1.41
